### ISSUE TITLE
celery beat scheduler  keeps restarting 

### ISSUE THREAD

**Issue by Prakashh21** [FNNDSC/ChRIS_ultron_backEnd#386] opened 2022-04-09 20:39 UTC
**output of `Docker compose logs scheduler`**

[schedulerlog.txt](https://github.com/FNNDSC/miniChRIS-docker/files/8457718/schedulerlog.txt)

**Comment by jennydaman** [comment] 2022-04-14 17:50
There is a bug where a stale `pid` file causes a crash loop if the `scheduler` container exits abnormally, for instance, if the container is killed. This usually also happens when the host is rebooted.

**Comment by Prakashh21** [comment] 2022-04-16 21:13
@jennydaman  apart from removing the scheduler container and running docker-compose up -d , what else could be the solution , can we do that , once the container scheduer container is crashed the celerybeat.pid file will automatically get deleted ?

**Comment by fortune-max** [comment] 2022-04-18 20:47
I have taken a look at this but just seeing you're assigned. There are some approaches I thought of as I was facing the same issue.

1. [My preferred choice] Do not supply a path for the pidfile parameter for celerybeat `--pidfile=` 
2. Use a folder mounted as tmpfs from `mount`'s output. As `/tmp` and `/var/tmp` still persist in docker after a reboot/crash, I think using a `/dev` folder like `/dev/shm` would do. So set `--pidfile=/dev/shm/celerybeat.pid`
3. As part of the Dockerfile add a command to delete the file when initializing and before it runs. `RUN rm /home/localuser/celerybeat.pid`

**Comment by Prakashh21** [comment] 2022-04-19 06:02
@fortune-max thanks for the feedback , what I initially thought and tried was to remove the celerybeat.pid file when the scheduler container starts, added  command it to the docker compose file , it worked for me ! , using tmpfs seems interesting... I'll try it.

**Comment by fortune-max** [comment] 2022-04-19 07:15
Oh nice, I'm only just learning Docker for the first time and thought the Dockerfile was the only setup file involved. Removing it using docker compose is a pretty neat approach. Thanks for sharing!

**Comment by Prakashh21** [comment] 2022-04-19 07:23
@fortune-max you're welcome , I am also new to docker .. , hey there is another issue similiar to this , with the chris_store_ui container , check it out ..  https://github.com/FNNDSC/miniChRIS-docker/issues/6

**Comment by fortune-max** [comment] 2022-04-19 07:27
Nice, just took a look. Was curious about why it was breaking locally as well. Will effect a fix locally so my install is more stable. Thanks for the heads up!

**Comment by Prakashh21** [comment] 2022-04-19 08:01
both the containers , chris_ui and chris_store_ui are serving static files using sirv , they should be creating some file inside the container which accounts for the user , I'm just trying to find where , I tried removing the --quiet flag to see the logs , but I didn't get any clues from there , @fortune-max  if you find any relevant info regarding this then please let me know as well..


![Screenshot from 2022-04-19 13-00-14](https://user-images.githubusercontent.com/90280586/163954109-8bb3ffb7-5d17-4fd4-ad1a-6682434f4dbc.png)

**Comment by fortune-max** [comment] 2022-04-19 09:58
Sure, I'll let you know if I'm able to get any insights on it as well.

**Comment by jennydaman** [comment] 2022-04-26 18:07
To summarize:

The `--pidfile` argument for the `scheduler` service (celery beat) prevents multiple instances from running, however this isn't a good solution because the container orchestrator/scheduler (Kubernetes, docker-compose, docker swarm) should be responsible for guaranteeing that exactly one replicate of this container must exist at all times.

The problem with the ChRIS_store_ui container is not related.

**Comment by devbird007** [comment] 2023-03-07 08:38
> To summarize:
> 
> The `--pidfile` argument for the `scheduler` service (celery beat) prevents multiple instances from running, however this isn't a good solution because the container orchestrator/scheduler (Kubernetes, docker-compose, docker swarm) should be responsible for guaranteeing that exactly one replicate of this container must exist at all times.
> 
> The problem with the ChRIS_store_ui container is not related.

I am an outreachy intern for the May2023 cohort. I am good with docker and would like to be assigned this project.

**Comment by jennydaman** [comment] 2023-03-17 11:02
@devbird007 what are the steps you've taken in attempt to reproduce the issue? have you tried either killing the container or rebooting, as per above https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/386#issuecomment-1099466552?

**Comment by devbird007** [comment] 2023-04-03 10:09
Hi @jennydaman, I was eventually able to reproduce the issue, and because I didn't understand what a celery beat scheduler was it took me some time to figure out. Nonetheless I have been able to solve the issue and it no longer restarts when the container is killed suddenly. I have also tagged my PR where I solve this issue, it's just above this comment.

**Comment by devbird007** [comment] 2023-04-03 21:31
Hi @jennydaman, I chose /dev/shm out of the list the previous contributor suggested because I wasn't completely comfortable with just deleting off the `--pidfile` parameter.

I figured if a process needs the pidfile it is at least still accessible, but now in a tmpfs where it isn't retained if the scheduler exits abruptly.

**Comment by jennydaman** [comment] 2023-04-03 23:41
@devbird007 I think it is safe to go with @fortune-max 's first suggestion, which is to omit `--pidfile` argument.

https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/386#issuecomment-1110099578

Above I've discussed the purpose of the `--pidfile` argument. It's not necessary in situations where we are using a container scheduler such as Docker or Kubernetes.

**Closed** 2023-04-04 16:56 UTC
Labels: bug, good first issue
